name: job_TES
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - numpy=1.19.5
  # - numpy=1.20.3
  - pandas=1.2.0
  # - pandas=1.3.1
  - pip=21.2.4
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - python=3.7
  - pytorch=1.7.1
  # - pytorch=1.9.0
  - cudatoolkit=10.1
  # - cudatoolkit=10.2
  # - pip:
  #   - setuptools==59.5.0
  #   - cython
  #   - tensorboard
  #   - tensorboardx==2.1
  #   - sparsesvd
  #   - torchdiffeq==0.2.0
  #   - cppimport==21.1.11
  #   - protobuf==3.19.0
  #   - cffi