name: job
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - pandas=1.2.0
  - pip=20.3.3
  - python=3.7.9
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - pytorch=1.7.1
  - cudatoolkit=10.1
  - numpy=1.19.5
  # - pip:
    # - setuptools==59.5.0
    # - cython
    # - tensorboard
    # - tensorboardx==2.1
    # - sparsesvd
    # - torchdiffeq==0.2.0
    # - cppimport==21.1.11
    # - protobuf==3.19.0
    # - cffi